#!/usr/bin/env julia
#
# Behavioral Change Detection for GPS Special Messages
#
# Applies CUSUM-based change-point detection to per-PRN and fleet-wide
# behavioral metrics (sentinel fraction, TEXT fraction, rotation rate,
# message diversity) at daily and weekly granularities.
#
# Usage:
#   julia --project analyze_behavioral_changes.jl [messages.duckdb]
#
# Output:
#   - Populates behavioral_metrics and behavioral_change_points tables in the DB
#   - Writes analysis_output/behavioral_changes_report.md

include(joinpath(@__DIR__, "..", "src", "GPSSpecialMessages.jl"))
using .GPSSpecialMessages

using DuckDB
using DataFrames
using Dates
using Printf

# ── Constants ─────────────────────────────────────────────────────────────────

const DEFAULT_DB = "data/messages.duckdb"
const OUTPUT_DIR = get(ENV, "REPORTS_DIR", joinpath(@__DIR__, "reports"))
const REPORT_FILE = joinpath(OUTPUT_DIR, "behavioral_changes.md")

# CUSUM parameters (standard industrial values)
const CUSUM_SLACK     = 0.5
const CUSUM_THRESHOLD = 5.0

# Coordination threshold: ≥8 PRNs (25 % of constellation) within ±3 days
const COORD_MIN_PRNS   = 8
const COORD_WINDOW_DAYS = 3

# Metric display names
const METRIC_LABELS = Dict(
    "sentinel_fraction"    => "Sentinel fraction",
    "text_fraction"        => "TEXT-prefix fraction",
    "observation_count"    => "Observations per period",
    "transition_count"     => "Transitions per week",
    "unique_message_count" => "Unique messages per week",
    "mean_duration_hours"  => "Mean message duration (hours)",
)

# ── Helpers ───────────────────────────────────────────────────────────────────

function fmt_date(dt::DateTime)
    Dates.format(dt, "yyyy-mm-dd")
end

function fmt_pct(x)
    ismissing(x) ? "—" : @sprintf("%.1f%%", 100.0 * Float64(x))
end

# ── Main ──────────────────────────────────────────────────────────────────────

function main()
    db_path = length(ARGS) >= 1 ? ARGS[1] : DEFAULT_DB
    isfile(db_path) || error("Database not found: $db_path")

    println("Opening database: $db_path")
    db = DuckDB.DB(db_path)

    # ── Step 1: Create tables ────────────────────────────────────────────
    println("Creating behavioral tables…")
    create_behavioral_tables!(db)

    # ── Step 2: Compute metrics ──────────────────────────────────────────
    println("Computing behavioral metrics (daily + weekly)…")
    metrics_df = compute_behavioral_metrics(db; granularities=[:daily, :weekly])
    println("  → $(nrow(metrics_df)) metric rows")

    # ── Step 3: Save metrics ─────────────────────────────────────────────
    println("Saving behavioral metrics to database…")
    save_behavioral_metrics!(db, metrics_df)

    # ── Step 4: Detect change points ─────────────────────────────────────
    println("Running CUSUM change-point detection…")
    change_points_df = detect_behavioral_change_points(
        metrics_df;
        slack                  = CUSUM_SLACK,
        threshold              = CUSUM_THRESHOLD,
        coordinated_min_prns   = COORD_MIN_PRNS,
        coordinated_window_days = COORD_WINDOW_DAYS,
    )
    println("  → $(nrow(change_points_df)) change points detected")

    # ── Step 5: Save change points ───────────────────────────────────────
    println("Saving change points to database…")
    save_behavioral_change_points!(db, change_points_df)

    # ── Step 6: Generate report ──────────────────────────────────────────
    println("Generating report → $REPORT_FILE")
    mkpath(OUTPUT_DIR)
    write_report(metrics_df, change_points_df, db_path)

    close(db)
    println("Done.")
end

# ── Report generation ─────────────────────────────────────────────────────────

function write_report(metrics_df::DataFrame, cp_df::DataFrame, db_path::String)
    open(REPORT_FILE, "w") do io
        ts = Dates.format(now(UTC), dateformat"yyyy-mm-ddTHH:MM:SS") * "Z"
        script = basename(@__FILE__)
        println(io, "<!-- AUTO-GENERATED by $script on $ts from $db_path — do not edit by hand -->")
        println(io)
        println(io, "# Behavioral Change Detection — GPS Special Messages")
        println(io)

        # ── Section 1: Summary ───────────────────────────────────────────
        println(io, "## 1. Summary")
        println(io)

        if isempty(metrics_df)
            println(io, "*No behavioral metrics could be computed (empty database?).*")
        else
            daily_rows  = filter(r -> r.granularity == "daily",  metrics_df)
            weekly_rows = filter(r -> r.granularity == "weekly", metrics_df)
            all_periods = filter(r -> r.prn == 0, metrics_df)

            if !isempty(all_periods)
                min_date = minimum(all_periods.period_start)
                max_date = maximum(all_periods.period_start)
                println(io, "- **Data span**: $(fmt_date(min_date)) to $(fmt_date(max_date))")
            end

            println(io, "- **Daily metric rows**: $(nrow(daily_rows))")
            println(io, "- **Weekly metric rows**: $(nrow(weekly_rows))")
            println(io, "- **Total change points detected**: $(nrow(cp_df))")

            if !isempty(cp_df)
                coord_count = sum(cp_df.is_coordinated)
                println(io, "- **Coordinated events** (≥$COORD_MIN_PRNS PRNs within ±$COORD_WINDOW_DAYS days): $coord_count")

                by_metric = combine(groupby(cp_df, :metric), nrow => :count)
                # Tie-break by :metric so equal counts order deterministically.
                sort!(by_metric, [order(:count, rev=true), :metric])
                println(io)
                println(io, "| Metric | Change points |")
                println(io, "|---|---|")
                for row in eachrow(by_metric)
                    label = get(METRIC_LABELS, row.metric, row.metric)
                    println(io, "| $label | $(row.count) |")
                end
            end
        end
        println(io)

        # ── Section 2: Fleet-wide coordinated timeline ───────────────────
        println(io, "## 2. Fleet-wide Coordinated Events")
        println(io)

        coord_events = isempty(cp_df) ? DataFrame() :
            filter(r -> r.is_coordinated && r.prn != 0, cp_df)

        if isempty(coord_events)
            println(io, "*No coordinated events detected.*")
        else
            # De-duplicate: same date+metric may appear from multiple PRNs
            dedup = combine(
                groupby(coord_events, [:detected_at, :metric, :direction]),
                :coordinated_prn_count => maximum => :prn_count,
                :granularity => first => :granularity,
            )
            # Total order over the groupby keys → deterministic across runs.
            sort!(dedup, [:detected_at, :metric, :direction])

            println(io, "Events where ≥$COORD_MIN_PRNS PRNs show a simultaneous change in the same metric:")
            println(io)
            println(io, "| Date | Granularity | Metric | Direction | PRNs |")
            println(io, "|---|---|---|---|---|")
            for row in eachrow(dedup)
                label = get(METRIC_LABELS, row.metric, row.metric)
                println(io, "| $(fmt_date(row.detected_at)) | $(row.granularity) | $label | $(row.direction) | $(row.prn_count) |")
            end
        end
        println(io)

        # ── Section 3: Notable known events cross-reference ──────────────
        println(io, "## 3. Notable Known Events")
        println(io)
        println(io, "The following events were previously identified by manual or entropy analysis:")
        println(io)
        println(io, "| Event | Expected date | Detected? |")
        println(io, "|---|---|---|")

        known_events = [
            ("TEXT-prefix messages appear on PRN 1", DateTime(2023, 12, 1)),
            ("All-¬ sentinel disappears",            DateTime(2020, 1, 1)),
        ]

        for (label, approx_dt) in known_events
            detected = "No"
            if !isempty(cp_df)
                # Look for any detection within ±90 days
                window_ms = 90 * 24 * 3600 * 1000
                nearby = filter(r -> abs(Dates.value(r.detected_at - approx_dt)) <= window_ms, cp_df)
                if !isempty(nearby)
                    best = nearby[argmin(abs.(Dates.value.(nearby.detected_at .- approx_dt))), :]
                    detected = "Yes — $(fmt_date(best.detected_at)) ($(best.metric), PRN $(best.prn))"
                end
            end
            println(io, "| $label | $(fmt_date(approx_dt)) | $detected |")
        end
        println(io)

        # ── Section 4: Per-metric breakdown ──────────────────────────────
        println(io, "## 4. Per-metric Change Points")
        println(io)

        if isempty(cp_df)
            println(io, "*No change points detected.*")
        else
            for metric in sort(unique(cp_df.metric))
                label = get(METRIC_LABELS, metric, metric)
                println(io, "### $label")
                println(io)

                sub = filter(r -> r.metric == metric, cp_df)
                # Tie-break beyond :detected_at so the top-N slice is stable.
                sort!(sub, [:detected_at, :prn, :granularity, :direction])
                top_n = min(20, nrow(sub))

                println(io, "| Date | Granularity | PRN | Direction | Coordinated |")
                println(io, "|---|---|---|---|---|")
                for row in eachrow(sub[1:top_n, :])
                    prn_str = row.prn == 0 ? "Fleet" : string(row.prn)
                    coord_str = row.is_coordinated ? "Yes ($(row.coordinated_prn_count) PRNs)" : "No"
                    println(io, "| $(fmt_date(row.detected_at)) | $(row.granularity) | $prn_str | $(row.direction) | $coord_str |")
                end
                if nrow(sub) > top_n
                    println(io, "| *…$(nrow(sub) - top_n) more rows not shown* | | | | |")
                end
                println(io)
            end
        end

        # ── Section 5: Per-PRN summary ────────────────────────────────────
        println(io, "## 5. Per-PRN Change Point Summary")
        println(io)

        if isempty(cp_df)
            println(io, "*No change points detected.*")
        else
            per_prn = filter(r -> r.prn != 0, cp_df)
            if isempty(per_prn)
                println(io, "*No per-PRN change points detected.*")
            else
                prn_counts = combine(groupby(per_prn, :prn), nrow => :total_changes,
                                     :is_coordinated => sum => :coordinated_changes)
                # Tie-break by :prn so equal change counts order deterministically.
                sort!(prn_counts, [order(:total_changes, rev=true), :prn])

                println(io, "| PRN | Total changes | Coordinated |")
                println(io, "|---|---|---|")
                for row in eachrow(prn_counts)
                    println(io, "| $(row.prn) | $(row.total_changes) | $(row.coordinated_changes) |")
                end
            end
        end
        println(io)

        # ── CUSUM parameters note ─────────────────────────────────────────
        println(io, "---")
        println(io)
        println(io, "**CUSUM parameters**: slack k = $CUSUM_SLACK, threshold h = $CUSUM_THRESHOLD, " *
                    "reference period = first 20 % of valid observations.")
        println(io, "**Coordination threshold**: ≥$COORD_MIN_PRNS PRNs within ±$COORD_WINDOW_DAYS days.")
    end
end

main()
