#!/usr/bin/env julia
#
# Duplicates Audit
#
# Reports on two flavours of duplicates that the build pipeline records into
# `messages.duckdb`:
#
#   1. Conflicting duplicates: same (datetime, prn) but different message
#      content. None should exist for this dataset; their presence would
#      indicate multi-receiver disagreement (geographic targeting evidence).
#      Tracked in the `duplicate_observations` table.
#
#   2. Identical duplicates: same (datetime, prn, message_hash) appearing in
#      multiple Arrow source files. Expected: GFZ reprocessed days 91–97 of
#      2008. Tracked in the `identical_duplicates` table.
#
# Usage:
#   julia --project analysis/duplicates_audit.jl [messages.duckdb]
#
# Writes analysis/reports/duplicates_audit.md.

include(joinpath(@__DIR__, "..", "src", "GPSSpecialMessages.jl"))
using .GPSSpecialMessages

using DuckDB
using Dates
using Printf

const DEFAULT_DB = "data/messages.duckdb"
const OUTPUT_DIR = get(ENV, "REPORTS_DIR", joinpath(@__DIR__, "reports"))
const REPORT_FILE = joinpath(OUTPUT_DIR, "duplicates_audit.md")

function main()
    db_path = length(ARGS) >= 1 ? ARGS[1] : DEFAULT_DB

    if !isfile(db_path)
        println(stderr, "Error: Database '$db_path' not found")
        exit(1)
    end

    println(stderr, "Duplicates Audit")
    println(stderr, "================")
    println(stderr, "Database: $db_path")
    println(stderr, "")

    db = DuckDB.DB(db_path; readonly=true)

    total_messages    = get_message_count(db)
    unique_messages   = get_unique_message_count(db)
    conflicting_count = get_duplicate_count(db)
    identical_count   = get_identical_duplicate_count(db)
    identical_total   = get_total_identical_occurrences(db)

    println(stderr, "Total observations:     $(total_messages)")
    println(stderr, "Unique messages:        $(unique_messages)")
    println(stderr, "Conflicting duplicates: $(conflicting_count)")
    println(stderr, "Identical duplicates:   $(identical_count) keys / $(identical_total) total occurrences")

    # Per-PRN distribution of identical duplicates
    prn_dist = DBInterface.execute(db, """
        SELECT prn, COUNT(*) AS keys, SUM(occurrence_count) AS occurrences
        FROM identical_duplicates
        GROUP BY prn
        ORDER BY occurrences DESC NULLS LAST, prn
    """)

    # Year/day-of-year buckets where identical duplicates concentrate
    doy_dist = DBInterface.execute(db, """
        SELECT
            EXTRACT(YEAR FROM datetime)::INT AS year,
            DATE_TRUNC('day', datetime)::DATE AS day,
            COUNT(*) AS keys,
            SUM(occurrence_count) AS occurrences
        FROM identical_duplicates
        GROUP BY year, day
        ORDER BY occurrences DESC, day
        LIMIT 20
    """)

    DBInterface.close!(db)

    mkpath(OUTPUT_DIR)
    open(REPORT_FILE, "w") do io
        ts = Dates.format(now(UTC), dateformat"yyyy-mm-ddTHH:MM:SS") * "Z"
        println(io, "<!-- AUTO-GENERATED by analysis/duplicates_audit.jl on $ts — do not edit by hand -->")
        println(io, "")
        println(io, "# Duplicates Audit")
        println(io, "")
        println(io, "## Headline figures")
        println(io, "")
        @printf(io, "- Total observations:        **%d**\n", total_messages)
        @printf(io, "- Unique message hashes:     **%d**\n", unique_messages)
        @printf(io, "- Conflicting duplicates:    **%d**  (same `(datetime, prn)`, different message)\n", conflicting_count)
        @printf(io, "- Identical duplicate keys:  **%d**  (same `(datetime, prn, message_hash)` across multiple source files)\n", identical_count)
        @printf(io, "- Identical occurrences:     **%d**  (sum of `occurrence_count` over those keys)\n", identical_total)
        println(io, "")

        println(io, "## Conflicting duplicates")
        println(io, "")
        if conflicting_count == 0
            println(io, "None. The dataset is consistent: no `(datetime, prn)` ever maps to two different message contents. This is evidence *against* geographic targeting on the L1 C/A special-message field.")
        else
            println(io, "**$conflicting_count conflicting pairs found.** This warrants investigation; cross-receiver disagreement could indicate geographic restriction.")
        end
        println(io, "")

        println(io, "## Identical duplicates")
        println(io, "")
        if identical_count == 0
            println(io, "No identical duplicates: every `(datetime, prn, message_hash)` appears in exactly one Arrow file.")
        else
            println(io, "Identical duplicates arise when the GFZ archive contains both an original and a reprocessed copy of the same daily file. Analysis of the dataset confirmed this: entire 300-bit subframes are byte-for-byte identical between the two copies.")
            println(io, "")
            println(io, "### Top days by occurrence count")
            println(io, "")
            println(io, "| Year | Day | Distinct keys | Occurrences |")
            println(io, "|------|-----|---------------|-------------|")
            for row in doy_dist
                @printf(io, "| %d | %s | %d | %d |\n",
                        Int(row.year),
                        string(row.day),
                        Int(row.keys),
                        Int(row.occurrences))
            end
            println(io, "")
            println(io, "### Per-PRN distribution")
            println(io, "")
            println(io, "| PRN | Distinct keys | Occurrences |")
            println(io, "|-----|---------------|-------------|")
            for row in prn_dist
                @printf(io, "| %d | %d | %d |\n",
                        Int(row.prn),
                        Int(row.keys),
                        Int(row.occurrences))
            end
        end
        println(io, "")
    end

    println(stderr, "")
    println(stderr, "Wrote report: $REPORT_FILE")
end

if abspath(PROGRAM_FILE) == @__FILE__
    main()
end
