#!/usr/bin/env julia
#
# PPM-D Marginal Compression Entropy Analysis
#
# Uses Prediction by Partial Matching (PPM-D) with exclusion, up to a
# configurable context order (default 8). Leave-one-out scoring: for each
# message M, the model is trained on all other messages, then M is scored
# as sum(-log2(P(byte_i | context))) giving fractional-bit precision that
# captures both character-level statistics and shared substring patterns.
#
# Usage:
#   julia --project analysis/marginal_entropy_ppm.jl [messages.duckdb] [max_order]
#
# Writes analysis/reports/marginal_entropy_ppm.md.

include(joinpath(@__DIR__, "..", "src", "GPSSpecialMessages.jl"))
using .GPSSpecialMessages
include(joinpath(@__DIR__, "..", "src", "ppm_model.jl"))
using .PPMEntropy
using DuckDB
using Dates
using Printf
using Statistics

const DEFAULT_DB  = "data/messages.duckdb"
const OUTPUT_DIR  = get(ENV, "REPORTS_DIR", joinpath(@__DIR__, "reports"))
const REPORT_FILE = joinpath(OUTPUT_DIR, "marginal_entropy_ppm.md")

# Backticks in raw text would break inline code spans inside the Markdown
# tables; replace with the unicode ` look-alike. Pipes don't appear in the
# GPS alphabet so no escaping needed.
sanitize(s::AbstractString) = replace(s, "`" => "ˋ")

function main()
    db_path   = length(ARGS) >= 1 ? ARGS[1] : DEFAULT_DB
    max_order = length(ARGS) >= 2 ? parse(Int, ARGS[2]) : 8

    if !isfile(db_path)
        println(stderr, "Error: Database '$db_path' not found")
        exit(1)
    end

    println(stderr, "PPM-D Marginal Compression Entropy (order $max_order)")
    println(stderr, "=" ^ 50)

    db = DuckDB.DB(db_path; readonly=true)

    result = DBInterface.execute(db, """
        SELECT
            ascii_message,
            raw_bytes,
            entropy,
            COUNT(*) as observations,
            MIN(datetime)::VARCHAR as first_date,
            MAX(datetime)::VARCHAR as last_date,
            COUNT(DISTINCT prn) as prns
        FROM special_messages
        GROUP BY ascii_message, raw_bytes, entropy
        ORDER BY ascii_message
    """)

    messages = NamedTuple{(:text, :raw, :entropy, :obs, :first, :last, :prns),
                          Tuple{String, Vector{UInt8}, Float64, Int, String, String, Int}}[]

    for row in result
        push!(messages, (
            text    = string(row.ascii_message),
            raw     = Vector{UInt8}(row.raw_bytes),
            entropy = Float64(row.entropy),
            obs     = Int(row.observations),
            first   = string(row.first_date)[1:10],
            last    = string(row.last_date)[1:10],
            prns    = Int(row.prns),
        ))
    end

    DBInterface.close!(db)

    n = length(messages)
    MSG_LEN = 22
    println(stderr, "Unique messages: $n")

    # Build full PPM model from all messages
    println(stderr, "Building PPM-D model (order $max_order)...")
    model = PPMModel(max_order)
    for m in messages
        update!(model, m.raw)
    end

    # Leave-one-out scoring
    println(stderr, "Scoring $n messages (leave-one-out)...")
    marginal_bits = Vector{Float64}(undef, n)

    for i in 1:n
        raw = messages[i].raw
        update!(model, raw; delta=-1)        # remove
        marginal_bits[i] = score_sequence(model, raw)
        update!(model, raw; delta=+1)        # restore
        if i % 500 == 0
            println(stderr, "  $i / $n")
        end
    end

    println(stderr, "Done.")
    println(stderr, "Finding repeating substrings...")
    raw_list = [m.raw for m in messages]
    shared = find_repeated_substrings(raw_list; min_len=6)
    println(stderr, "  → $(length(shared)) maximal shared substrings")

    order = sortperm(marginal_bits)
    p10 = quantile(marginal_bits, 0.10)
    p90 = quantile(marginal_bits, 0.90)

    mkpath(OUTPUT_DIR)
    open(REPORT_FILE, "w") do io
        ts = Dates.format(now(UTC), dateformat"yyyy-mm-ddTHH:MM:SS") * "Z"
        println(io, "<!-- AUTO-GENERATED by analysis/marginal_entropy_ppm.jl on $ts from $db_path — do not edit by hand -->")
        println(io, "")
        println(io, "# PPM-D Marginal Compression Entropy")
        println(io, "")
        println(io, "- **Method**: PPM-D with exclusion, leave-one-out scoring")
        println(io, "- **Max order**: $max_order")
        println(io, "- **Corpus**: $n unique messages, $(n * MSG_LEN) bytes")
        println(io, "")

        # ── Summary ──────────────────────────────────────────────────────
        println(io, "## 1. Summary statistics")
        println(io, "")
        println(io, "| Statistic | Value |")
        println(io, "|---|---|")
        @printf(io, "| Mean     | %.2f bits |\n", mean(marginal_bits))
        @printf(io, "| Median   | %.2f bits |\n", median(marginal_bits))
        @printf(io, "| Std      | %.2f bits |\n", std(marginal_bits))
        @printf(io, "| 10th pct | %.2f bits |\n", p10)
        @printf(io, "| 90th pct | %.2f bits |\n", p90)
        @printf(io, "| Min      | %.2f bits — `%s` |\n",
                minimum(marginal_bits), sanitize(messages[order[1]].text))
        @printf(io, "| Max      | %.2f bits — `%s` |\n",
                maximum(marginal_bits), sanitize(messages[order[end]].text))
        println(io, "")

        # ── Sorted results (code block; fig2 parser reads this) ───────────
        println(io, "## 2. Sorted results (full corpus)")
        println(io, "")
        println(io, "Each row is one unique message. `m_bits` is the leave-one-out PPM-D")
        println(io, "marginal coding cost; `s_ent` is the per-message Shannon entropy.")
        println(io, "")
        println(io, "```")
        @printf(io, "%-12s %6s  %8s  %6s  %4s  %-12s  %s\n",
                "first_date", "obs", "m_bits", "s_ent", "prns", "last_date", "message")
        println(io, "-" ^ 110)
        for i in order
            m = messages[i]
            @printf(io, "%-12s %6d  %8.2f  %6.3f  %4d  %-12s  |%s|\n",
                    m.first, m.obs, marginal_bits[i], m.entropy, m.prns, m.last, m.text)
        end
        println(io, "```")
        println(io, "")

        # ── Low tail ─────────────────────────────────────────────────────
        @printf(io, "## 3. Low marginal entropy (below 10th percentile = %.2f bits)\n", p10)
        println(io, "")
        println(io, "| m_bits | obs | prns | first_date | message |")
        println(io, "|---|---|---|---|---|")
        for i in order
            marginal_bits[i] > p10 && break
            m = messages[i]
            @printf(io, "| %.2f | %d | %d | %s | `%s` |\n",
                    marginal_bits[i], m.obs, m.prns, m.first, sanitize(m.text))
        end
        println(io, "")

        # ── High tail ────────────────────────────────────────────────────
        @printf(io, "## 4. High marginal entropy (above 90th percentile = %.2f bits)\n", p90)
        println(io, "")
        println(io, "| m_bits | obs | prns | first_date | message |")
        println(io, "|---|---|---|---|---|")
        for i in reverse(order)
            marginal_bits[i] < p90 && break
            m = messages[i]
            @printf(io, "| %.2f | %d | %d | %s | `%s` |\n",
                    marginal_bits[i], m.obs, m.prns, m.first, sanitize(m.text))
        end
        println(io, "")

        # ── Substring catalogue ──────────────────────────────────────────
        println(io, "## 5. Repeating substrings (length ≥ 6, shared by ≥ 2 messages)")
        println(io, "")
        println(io, "Found $(length(shared)) maximal shared substrings.")
        println(io, "")

        for (j, entry) in enumerate(shared)
            sub = entry.bytes
            occs = entry.occurrences
            msg_indices = sort(unique(first.(occs)))
            hex_str = join([@sprintf("%02x", b) for b in sub], "")
            display_str = String([0x20 <= b <= 0x7e ? Char(b) : '.' for b in sub])

            @printf(io, "### 5.%d. %d bytes — `%s` (`%s`)\n",
                    j, length(sub), sanitize(display_str), hex_str)
            println(io, "")
            println(io, "| msg # | positions | m_bits | obs | first_date | full message |")
            println(io, "|---|---|---|---|---|---|")
            for mi in msg_indices
                positions = sort([sp for (m, sp) in occs if m == mi])
                m = messages[mi]
                pos_str = join(["$(p)–$(p+length(sub)-1)" for p in positions], ", ")
                @printf(io, "| %d | %s | %.2f | %d | %s | `%s` |\n",
                        mi, pos_str, marginal_bits[mi], m.obs, m.first, sanitize(m.text))
            end
            println(io, "")
        end
    end

    println(stderr, "")
    println(stderr, "Wrote report: $REPORT_FILE")
end

if abspath(PROGRAM_FILE) == @__FILE__
    main()
end
